-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 14:43:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE `mydb` ;

DROP TABLE IF EXISTS `mydb`.`user` ;
DROP TABLE IF EXISTS `mydb`.`credential` ;
DROP TABLE IF EXISTS `mydb`.`address` ;
DROP TABLE IF EXISTS `mydb`.`artist` ;
DROP TABLE IF EXISTS `mydb`.`event` ;
DROP TABLE IF EXISTS `mydb`.`ticket_event` ;
DROP TABLE IF EXISTS `mydb`.`order_event` ;
DROP TABLE IF EXISTS `mydb`.`passage_type` ;
DROP TABLE IF EXISTS `mydb`.`passage` ;
DROP TABLE IF EXISTS `mydb`.`ticket_passage` ;
DROP TABLE IF EXISTS `mydb`.`order_passage` ;
-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`user` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`credential`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`credential` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_credential_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`credential` (`id` ASC) VISIBLE;

CREATE INDEX `fk_credential_user_idx` ON `mydb`.`credential` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`adress`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`address` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`artist`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`artist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`artist` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME(3) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  `artist_id` INT NOT NULL,
  `event_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_event_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_artist`
    FOREIGN KEY (`artist_id`)
    REFERENCES `mydb`.`artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`event` (`id` ASC) VISIBLE;

CREATE INDEX `fk_event_address_idx` ON `mydb`.`event` (`address_id` ASC) VISIBLE;

CREATE INDEX `fk_event_artist_idx` ON `mydb`.`event` (`artist_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ticket_event`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`ticket_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `row` VARCHAR(45) NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `free` TINYINT NOT NULL,
  `place` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ticket_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`ticket_event` (`id` ASC) VISIBLE;

CREATE INDEX `fk_ticket_event_idx` ON `mydb`.`ticket_event` (`event_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`order_event`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`order_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payed` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  `delivery` VARCHAR(45) NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_event_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_event_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`order_event` (`id` ASC) VISIBLE;

CREATE INDEX `fk_order_event_user_idx` ON `mydb`.`order_event` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_order_event_event_idx` ON `mydb`.`order_event` (`event_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`passage`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`passage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `arrive_city` VARCHAR(45) NOT NULL,
  `departure_city` VARCHAR(45) NOT NULL,
  `arrive_time` VARCHAR(45) NOT NULL,
  `departure_time` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `passage_type` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`passage` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ticket_passage`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`ticket_passage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `row` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `free` TINYINT NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `passage_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ticket_passage`
    FOREIGN KEY (`passage_id`)
    REFERENCES `mydb`.`passage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`ticket_passage` (`id` ASC) VISIBLE;

CREATE INDEX `fk_ticket_passage_idx` ON `mydb`.`ticket_passage` (`passage_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`order_passage`
-- -----------------------------------------------------

CREATE TABLE `mydb`.`order_passage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payed` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  `delivery` VARCHAR(45) NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `passage_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_passage_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_passage`
    FOREIGN KEY (`passage_id`)
    REFERENCES `mydb`.`passage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`order_passage` (`id` ASC) VISIBLE;

CREATE INDEX `fk_order_passage_user_idx` ON `mydb`.`order_passage` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_order_passage_idx` ON `mydb`.`order_passage` (`passage_id` ASC) VISIBLE;
